image:
  registry: docker.io
  repository: bitnamilegacy/clickhouse
  tag: 25.7.5
shards: 1
replicaCount: 3
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - prd-insw04
                - prd-insw05
                - prd-insw06
                - prd-insw07


keeper:
  image:
      registry: docker.io
      repository: bitnamilegacy/clickhouse-keeper
      tag: 25.7.5-debian-12-r0
  replicaCount: 3
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - prd-insw04
                  - prd-insw05
                  - prd-insw06
                  - prd-insw07


persistence:
  storageClass: "hpe-rwo"
  size: "500Gi"

auth:
  username: admin
  password: xxx

resources:
  limits:
    memory: 64Gi
  requests:
    cpu: "4"
    memory: 32Gi

configdFiles:
  logs.xml: |
    <yandex>
        <query_log>
          <database>system</database>
          <table>query_log</table>
        </query_log>
    </yandex>
