image:
  registry: docker.io
  repository: dbeaver/cloudbeaver
  tag: 25.2.1
ingress:
  enabled: true
  hostname: cloudbeaver.xxx.com
  ingressClassName: "nginx"
  annotations:
    nginx.org/websocket-services: cloudbeaver
persistence:
  storageClass: "hpe-rwo"

resources:
  requests:
    cpu: 2
    memory: 512Mi
  limits:
    cpu: 3
    memory: 1024Mi

# extraEnvVars:
#   - name: CB