apiVersion: v1
kind: Secret
metadata:
  name: hpe-backend
  namespace: hpe-storage
stringData:
  serviceName: alletra6000-csp-svc
  servicePort: "8080"
  # HPE Alletra/3PAR management IP or hostname
  backend: "<HPE_BACKEND_HOST>"
  username: "<HPE_BACKEND_USERNAME>"
  password: "<HPE_BACKEND_PASSWORD>"
