nameOverride: "" # use when install in same namespace
replicaCount: 1

image:
  repository: cloudlena/s3manager
  pullPolicy: IfNotPresent
  tag: "latest"

ports:
  - name: http
    containerPort: 8080
    servicePort: 80
    protocol: TCP

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: bucket.xxx.com
      paths:
        - path: /
          pathType: Prefix
          port: 80
  tls: []

configMap:
  enabled: true
  data:
    ENDPOINT: "minio:9000"
    ACCESS_KEY_ID: "admin"
    SECRET_ACCESS_KEY: "qwer1234"
    USE_SSL: "false"


