nameOverride: "mc" # use when install in same namespace
replicaCount: 1

image:
  repository: cloudlena/s3manager
  pullPolicy: IfNotPresent
  tag: "latest"

ports:
  - name: http
    containerPort: 8080
    servicePort: 80
    protocol: TCP

ingress:
  enabled: true
  className: nginx
  # # if subdomain is used, the host should be like: subdomain.domain.com
  # annotaions: {}

  # if path is used, the host should be like: domain.com, and the path should be like: /subpath
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: 'true'
  hosts:
    - host: wn-a-prd-ai-k8s.tlnw.magnecomp.com
      paths:
        # # if subdomain is used, the path should be like: /
        # - path: /
        #   pathType: Prefix
        #   port: 80
        # if path is used, the path should be like: /subpath(/|$)(.*)
        - path: /s3-manager/mc(/|$)(.*)
          pathType: ImplementationSpecific
          port: 80

configMap:
  enabled: true
  data:
    ENDPOINT: "<ENDPOINT_URL>"
    ACCESS_KEY_ID: "<YOUR_ACCESS_KEY_ID>"
    SECRET_ACCESS_KEY: "<YOUR_SECRET_ACCESS_KEY>"
    USE_SSL: "true"
    # if path is used, the ROOT_URL should be like: /subpath
    ROOT_URL: "/s3-manager/mc"
    # # if subdomain is used, the ROOT_URL should be like: /
    # ROOT_URL: "/"


